name: Deploy to Server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run /home/artem/deploy.sh over SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          host_fingerprint: ${{ secrets.HOST_FINGERPRINT }}
          script_stop: true
          # login shell + абсолютный путь к скрипту
          script: |
            set -euo pipefail
            bash -lc '/home/artem/deploy.sh'
